version: '2'

volumes:
  wordpress_db:
    driver: local

services:
  wpdb:
    image: mysql:5.7
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${injectedPass}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${injectedPass}
  wordpress:
    depends_on:
      - wpdb
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ${injectedPass}
