---
- :name: puppetserver 
  :basebox: bento/centos-7
  :bootstrap: centos7_puppetmaster.sh
  :memory: 2048
  :aliases: 
    - puppet
    - puppetmaster.lab1
    - puppetca.lab1

- :name: devops01
  :basebox: centos/7
  :bootstrap: centos7_devops.sh 
  :memory: 4096
  :ip: 172.28.128.101
  :forward:
    - ["8080", "8080"]
    - ["3000", "3000"]
  :cpus: 4 
  :autostart: true
  :aliases:
    - git 
    - jenkins

- :name: devops02
  :basebox: ubuntu/xenial64
  :bootstrap: ubuntu_devops.sh
  :memory: 4096
  :ip: 172.28.128.102
  :forward:
    - ["8081", "8080"]
    - ["3001", "3000"]
  :cpus: 4
  :autostart: true

- :name: kub-master01
  :basebox: ubuntu/xenial64
  :bootstrap: ubuntu.sh
  :ip: 192.168.200.102
  :cpus: 2
  :memory: 2048
  :aliases:
    - kubernetes-master

- :name: kub-node01
  :basebox: ubuntu/xenial64 
  :bootstrap: ubuntu.sh
  :ip: 192.168.200.104
  :cpus: 2 
  :memory: 3075 

- :name: kub-node02
  :basebox: ubuntu/xenial64
  :bootstrap: ubuntu.sh
  :ip: 192.168.200.103
  :cpus: 2
  :memory: 3075 

- :name: microk8s 
  :basebox: ubuntu/xenial64
  :bootstrap: ubuntu.sh
  :cpus: 2
  :memory: 4096 
  :ip: 172.28.128.100

